#!/bin/sh 

# Als het goed is start dit ding de busbot op
# dit werkt vast goed

PID=`cat /tmp/busbot.pid`

kill ${PID}

cd ~/Documents/projects/busbot
source ./env/bin/activate
nohup python3 busbot.py > busbot.log & 

echo $! > /tmp/busbot.pid
